### ISSUE TITLE
quran4iphone.com is just down

### ISSUE THREAD

**Issue by alaasalama** [MomenYasser/ZikrApp#2]
quran4iphone.com server is down for about 3 days till now, so recitations depending on this server aren't working (Mishary Alafasy is the one I've tested), would appreciate if there is an option to switch to another server if the default server isn't reachable at the moment.

P.S. When I have some free time, I'll try to work on it.

Thanks.

**Comment by MomenYasser** [comment]
Thanks alaa for your notice ... i will switch alternative server by this weekend IsA

**Comment by MomenYasser** [comment]
Alaa plz update

**Comment by alaasalama** [comment]
Awesome man! thanks for the fast response!
